### PR TITLE
Update F# template to GA SDK & Remove dead using in C#

### PR DESCRIPTION
**Pull request by WilliamBerryiii**

### CODE REVIEW

**Comment by WilliamBerryiii** [comment]
Any updates on getting the updated template merged?

**Comment by WilliamBerryiii** [comment]
Hey All, any updates on accepting the PR?

**Comment by konichi3** [comment]
We apologize for taking a long time to respond. We will take this PR to review with the appropriate team and get back to you.

**Comment by marianan** [comment]
Thanks for your PR; at this time we are closing it as F# template is retiring.

**Pull request closed without merging**
